### ISSUE TITLE
:latest crashing out hard immediately on red-discord

### ISSUE THREAD

**Issue by jackjohnsonuk** [pejter/dockerfiles#3]
I've been running this docker for months now and all has been great; however some point yesterday it updated and has been crashing out on docker load now.  

Docker Log below:

```Traceback (most recent call last):
File "./red.py", line 12, in <module>
from discord.ext import commands
File "/usr/local/lib/python3.7/site-packages/discord/__init__.py", line 20, in <module>
from .client import Client, AppInfo, ChannelPermissions
File "/usr/local/lib/python3.7/site-packages/discord/client.py", line 42, in <module>
from .voice_client import VoiceClient
File "/usr/local/lib/python3.7/site-packages/discord/voice_client.py", line 43, in <module>
import websockets
File "/usr/local/lib/python3.7/site-packages/websockets/__init__.py", line 3, in <module>
from .client import *
File "/usr/local/lib/python3.7/site-packages/websockets/client.py", line 12, in <module>
from .protocol import CONNECTING, OPEN, WebSocketCommonProtocol
File "/usr/local/lib/python3.7/site-packages/websockets/protocol.py", line 17, in <module>
from .compatibility import asyncio_ensure_future
File "/usr/local/lib/python3.7/site-packages/websockets/compatibility.py", line 9
asyncio_ensure_future = asyncio.async # Python < 3.5
^
SyntaxError: invalid syntax
Installing cog dependencies...
```

Many Thanks

**Comment by jackjohnsonuk** [comment]
Thanks Peter
