### ISSUE TITLE
is this still working?

### ISSUE THREAD

**Issue by kieeps** [pejter/dockerfiles#4]
```
$ docker run -it --rm pejter/red-discordbot:alpine
Installing cog dependencies...
Creating data/red folder...
Creating empty disabled_commands.json...
Creating empty global_ignores.json...
Creating data/audio/cache folder...
Creating data/audio/localtracks folder...
Creating data/audio/sfx folder...
Creating default audio settings.json...
RuntimeError: Your opus library's bitness must match your python installation's bitness. They both must be either 32bit or 64bit.
[05/03/2019 12:48] ERROR red load_cogs 573: Your opus library's bitness must match your python installation's bitness. They both must be either 32bit or 64bit.
Traceback (most recent call last):
  File "./red.py", line 570, in load_cogs
    owner_cog._load_cog(extension)
  File "/app/cogs/owner.py", line 948, in _load_cog
    self.bot.load_extension(mod_obj.__name__)
  File "/usr/local/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 738, in load_extension
    lib.setup(self)
  File "/app/cogs/audio.py", line 2531, in setup
    "Your opus library's bitness must match your python installation's"
RuntimeError: Your opus library's bitness must match your python installation's bitness. They both must be either 32bit or 64bit.
Creating data/streams folder...
Creating empty twitch.json...
Creating empty hitbox.json...
Creating empty beam.json...
Creating empty picarto.json...
Creating empty settings.json...
Creating data/alias folder...
Creating default alias's aliases.json...
Creating data/customcom folder...
Creating empty commands.json...
Making repo downloads folder...
Creating default data/downloader/repos.json
Creating data/mod/ folder...
Creating empty ignorelist.json
Creating empty filter.json
Creating empty past_names.json
Creating empty past_nicknames.json
Creating empty settings.json
Creating empty modlog.json
Creating empty perms_cache.json
Creating empty settings.json...
Creating data/economy folder...
Creating default economy's settings.json...
Creating empty bank.json...

Failed to load: cogs.audio

Logging into Discord...
No credentials available to login.
[05/03/2019 12:48] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "./red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "./red.py", line 602, in main
    raise RuntimeError()
RuntimeError
Task was destroyed but it is pending!
task: <Task pending coro=<Streams.stream_checker() running at /app/cogs/streams.py:624> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f28c7392288>()]>>
```

cant seem to even get the image running, not any of the 3 variants you provide.

**Comment by pejter** [comment]
I'm still running my own instance with no problems, however I've not done the initial setup in a while. This won't be super high on my priority list but I'll try to look into it.

**Comment by kieeps** [comment]
that's OK :) i can set a LXC up and make the init config there and move it to the data volume.

Thanks for the insanely fast response :P

**Comment by pejter** [comment]
No problem, it's be nice if you could comment here if any more issues arise so I know if I can close this issue.

**Comment by kieeps** [comment]
hmmm...
```
$ docker run -it -v /apps/docker/Util-Red/data:/app/data -v /apps/docker/Util-Red/cogs:/app/cogs pejter/red-discordbot:alpine
Installing cog dependencies...
Traceback (most recent call last):
  File "./red.py", line 21, in <module>
    from cogs.utils.settings import Settings
ModuleNotFoundError: No module named 'cogs.utils'

```

> If you'd like to host-mount those volumes you can do so, but make sure to initialize the directories first using their respective folders from the source repository. Then you can run the container with:

im not entirely sure what folder to add in the bound folder from the source tbh...


Edit: kid just woke up, ill mess with it later tonight and get back to you so you can close the issue :-)

**Comment by kieeps** [comment]
Do you know where it looks for the settings.json?

That's usually specified at the setup but since it wont start without it i need to mount bind it in i guess :-D

**Comment by kieeps** [comment]
Ended up sticking to the LXC :-P its to much work setting it up without being able to run the setup itself im afraid
